### ISSUE TITLE
Error on running P4D2_2018_East/exercises/p4runtime/mycontroller.py

### ISSUE THREAD

**Issue by tamihiro** [p4lang/tutorials#150]
When I tried the tunnel counter didn't start to increment.
```
----- Reading tunnel counters -----
Traceback (most recent call last):
  File "./mycontroller.py", line 183, in <module>
    main(args.p4info, args.bmv2_json)
  File "./mycontroller.py", line 156, in main
    printCounter(p4info_helper, s1, "MyIngress.ingressTunnelCounter", 100)
  File "./mycontroller.py", line 109, in printCounter
    for response in sw.ReadCounters(p4info_helper.get_counters_id(counter_name), index):
  File "/home/admin/work/src/github.com/p4lang_tutorials/P4D2_2018_East/exercises/p4runtime/p4runtime_lib/switch.py", line 83, in ReadCounters
    counter_entry.index = index
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.2.0-py2.7.egg/google/protobuf/internal/python_message.py", line 722, in setter
    '"%s" in protocol message object.' % proto_field_name)
AttributeError: Assignment not allowed to composite field "index" in protocol message object.
```
I checked the [protobuf catalog](https://github.com/p4lang/PI/blob/master/proto/p4/p4runtime.proto#L266), and figured it would need to be fixed as suggested in [PR#149](https://github.com/p4lang/tutorials/pull/149).

With the fix, I can see it running ok.
```
----- Reading tunnel counters -----
s1 MyIngress.ingressTunnelCounter 100: 2 packets (196 bytes)
s2 MyIngress.egressTunnelCounter 100: 0 packets (0 bytes)
s2 MyIngress.ingressTunnelCounter 200: 0 packets (0 bytes)
s1 MyIngress.egressTunnelCounter 200: 0 packets (0 bytes)

----- Reading tunnel counters -----
s1 MyIngress.ingressTunnelCounter 100: 4 packets (392 bytes)
s2 MyIngress.egressTunnelCounter 100: 0 packets (0 bytes)
s2 MyIngress.ingressTunnelCounter 200: 0 packets (0 bytes)
s1 MyIngress.egressTunnelCounter 200: 0 packets (0 bytes)

```

**Comment by tamihiro** [comment]
Never mind, it's already been mentioned in [#147](https://github.com/p4lang/tutorials/pull/147/commits/b8f61898823847705658bba1deeaffbd3f6c77da).
