### ISSUE TITLE
Message type "p4.config.Table" has no field named "idle_timeout_behavior"

### ISSUE THREAD

**Issue by qiaokang92** [p4lang/tutorials#183]
Hi, when I type `make run` to run "basic" exercise, something wrong occurred:

$ make run
mkdir -p build pcaps logs
p4c-bm2-ss --p4v 16 --p4runtime-file build/basic.p4info --p4runtime-format text -o build/basic.json basic.p4
sudo python ../../utils/run_exercise.py -t topology.json -b simple_switch_grpc
Reading topology file.
Building mininet topology.
Switch port mapping:
s1:  1:h1	2:s2	3:s3
s2:  1:h2	2:s1	3:s3
s3:  1:h3	2:s1	3:s2
Configuring switch s3 using P4Runtime with file s3-runtime.json
 - Using P4Info file build/basic.p4info...
/home/qiaokang/p4-workspace/tutorials-master/exercises/basic/build/basic.p4info
Traceback (most recent call last):
  File "../../utils/run_exercise.py", line 408, in <module>
    exercise.run_exercise()
  File "../../utils/run_exercise.py", line 207, in run_exercise
    self.program_switches()
  File "../../utils/run_exercise.py", line 312, in program_switches
    self.program_switch_p4runtime(sw_name, sw_dict)
  File "../../utils/run_exercise.py", line 284, in program_switch_p4runtime
    proto_dump_fpath=outfile)
  File "/home/qiaokang/p4-workspace/tutorials-master/utils/p4runtime_lib/simple_controller.py", line 102, in program_switch
    p4info_helper = helper.P4InfoHelper(p4info_fpath)
  File "/home/qiaokang/p4-workspace/tutorials-master/utils/p4runtime_lib/helper.py", line 28, in __init__
    google.protobuf.text_format.Merge(p4info_f.read(), p4info)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 730, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 23:3 : Message type "p4.config.Table" has no field named "idle_timeout_behavior".
../../utils/Makefile:27: recipe for target 'run' failed
make: *** [run] Error 1

It seems the build/basic.p4info file is not generated correctly:

tables {
  preamble {
    id: 33574068
    name: "MyIngress.ipv4_lpm"
    alias: "ipv4_lpm"
  }
  match_fields {
    id: 1
    name: "hdr.ipv4.dstAddr"
    bitwidth: 32
    match_type: LPM
  }
  action_refs {
    id: 16799317
  }
  action_refs {
    id: 16805608
  }
  action_refs {
    id: 16800567
  }
  size: 1024
  **idle_timeout_behavior: NO_TIMEOUT**
}

Any idea on debugging this issue?

p4c-bm2-ss --version ==== Version 0.0.5
protoc --version   =====  libprotoc 3.6.0

**Comment by antoninbas** [comment]
Looks like you are using some incompatible versions of PI / the compiler / the tutorial code.
I recommend using the provided Vagrant VM to avoid any incompatibility issue (if you are already using the VM then this is a bug that we need to look into).
In the case of this specific issue, you may be able to solve it by updating PI (https://github.com/p4lang/PI) to master, but I cannot guarantee that you won't run into another issue after that.

**Comment by qiaokang92** [comment]
@antoninbas Thanks for your reply!

I have updated PI to latest version (git commit no. 279513efb) but the issue still exists. My tutorial / p4c are both the newest commit as well.

One more query: besides google driver, do we have any other ways to download the VM image? Google drive is too slow in China due to some well-known reasons.

Thanks,
Qiao

**Comment by antoninbas** [comment]
It seems that the tutorial exercises use the old versions of the P4Runtime packages (p4 and p4.config instead of p4.v1 and p4.config.v1).
Did you try building the VM yourself (https://github.com/p4lang/tutorials/blob/master/vm/Vagrantfile)? I don't think that requires any google drive access but I may be wrong.
Alternatively you can rollback to older versions of PI, p4c & bmv2, by using the shas provided in this script: https://github.com/p4lang/tutorials/blob/master/vm/user-bootstrap.sh#L9

**Comment by qiaokang92** [comment]
Thanks @antoninbas , I checkout 219b3d67299ec09b49f433d7341049256ab5f512 commit of PI, then this issue doesn't appear again.
