### ISSUE TITLE
basic_tunnel example starter code won't compile

### ISSUE THREAD

**Issue by mlda065** [p4lang/tutorials#196]
The readme for the basic_tunnel example says:

> Step 1: Run the (incomplete) starter code
>
> `make run`
>
> You should now see a Mininet command prompt

When I do `make run` I see 

```
Traceback (most recent call last):
  File "../../utils/run_exercise.py", line 408, in <module>
    exercise.run_exercise()
  File "../../utils/run_exercise.py", line 207, in run_exercise
    self.program_switches()
  File "../../utils/run_exercise.py", line 312, in program_switches
    self.program_switch_p4runtime(sw_name, sw_dict)
  File "../../utils/run_exercise.py", line 284, in program_switch_p4runtime
    proto_dump_fpath=outfile)
  File "/home/vagrant/tutorials/utils/p4runtime_lib/simple_controller.py", line 129, in program_switch
    insertTableEntry(sw, entry, p4info_helper)
  File "/home/vagrant/tutorials/utils/p4runtime_lib/simple_controller.py", line 148, in insertTableEntry
    priority=priority)
  File "/home/vagrant/tutorials/utils/p4runtime_lib/helper.py", line 171, in buildTableEntry
    table_entry.table_id = self.get_tables_id(table_name)
  File "/home/vagrant/tutorials/utils/p4runtime_lib/helper.py", line 64, in <lambda>
    return lambda name: self.get_id(primitive, name)
  File "/home/vagrant/tutorials/utils/p4runtime_lib/helper.py", line 50, in get_id
    return self.get(entity_type, name=name).preamble.id
  File "/home/vagrant/tutorials/utils/p4runtime_lib/helper.py", line 45, in get
    raise AttributeError("Could not find %r of type %s" % (name, entity_type))
AttributeError: Could not find 'MyIngress.myTunnel_exact' of type tables
../../utils/Makefile:27: recipe for target 'run' failed
make: *** [run] Error 1
```

So the starter code cannot be compiled.

Either the starter code should be fixed (e.g. adding an empty `myTunnel` table definition to `basic_tunnel.p4`) or the readme should be modified.

**Comment by jnfoster** [comment]
This issue was raised earlier. Either solution is fine with me. Maybe simplest to modify the README.
