### ISSUE TITLE
ImportError: No module named v1

### ISSUE THREAD

**Issue by ZhiYiFang** [p4lang/tutorials#298]
Hello.
After I have configured the environment, enter the "make run" command in the "/tutorials/exercises/basic" path and the following error occurs:

sudo python ../../utils/run_exercise.py -t pod-topo/topology.json -j build/basic.json -b simple_switch_grpc
Traceback (most recent call last):
  File "../../utils/run_exercise.py", line 33, in <module>
    import p4runtime_lib.simple_controller
  File "/home/zhiyifang/下载/p4/tutorials/utils/p4runtime_lib/simple_controller.py", line 22, in <module>
    import bmv2
  File "/home/zhiyifang/下载/p4/tutorials/utils/p4runtime_lib/bmv2.py", line 15, in <module>
    from switch import SwitchConnection
  File "/home/zhiyifang/下载/p4/tutorials/utils/p4runtime_lib/switch.py", line 20, in <module>
    from p4.v1 import p4runtime_pb2
ImportError: No module named v1
../../utils/Makefile:35: recipe for target 'run' failed
make: *** [run] Error 1

How can I solve this problem? Thank you!

**Comment by JerryBesT** [comment]
did you run ./root-bootstrap.sh and ./user-bootstrap.sh?

**Comment by ZhiYiFang** [comment]
I didn't run these scripts directly. I referenced the scripts and manually configured the environment.
