### ISSUE TITLE
IPv6 address cann't  WriteTableEntry()

### ISSUE THREAD

**Issue by aaapuuuuu** [p4lang/tutorials#338]
hello, 

I hope to achieve ipv4 to ipv6 tunnel, so I changed mytunnel to ipv6 based on the basic_tunnel experiment, and convert.py also changed to support ipv6, but when using s1-runtime.json to send the flow table, as long as If there is an IPv6 address, an error will be reported. The following is the traceback information. I think the reason is that the grpc client is not responding. If p4runtime and grpc support IPv6? Because I can successfully run the flow table by using cli, the p4 program should have no problems.

thank you so much!

```
- MyIngress.ipv4_lpm: hdr.ipv4.dstAddr=['10.0.2.2', 32] => MyIngress.tunnel_ingress(dstAddr6=2001::2, srcAddr6=2001::3)
Traceback (most recent call last):
  File "../../utils/run_exercise.py", line 409, in <module>
    exercise.run_exercise()
  File "../../utils/run_exercise.py", line 207, in run_exercise
    self.program_switches()
  File "../../utils/run_exercise.py", line 313, in program_switches
    self.program_switch_p4runtime(sw_name, sw_dict)
  File "../../utils/run_exercise.py", line 285, in program_switch_p4runtime
    proto_dump_fpath=outfile)
  File "/home/myp4/P4/tutorials/utils/p4runtime_lib/simple_controller.py", line 129, in program_switch
    insertTableEntry(sw, entry, p4info_helper)
  File "/home/myp4/P4/tutorials/utils/p4runtime_lib/simple_controller.py", line 150, in insertTableEntry
    sw.WriteTableEntry(table_entry)
  File "/home/myp4/P4/tutorials/utils/p4runtime_lib/switch.py", line 97, in WriteTableEntry
    self.client_stub.Write(request)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_interceptor.py", line 201, in __call__
    credentials=credentials)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_interceptor.py", line 225, in _with_call
    continuation, client_call_details, request)
  File "/home/myp4/P4/tutorials/utils/p4runtime_lib/switch.py", line 155, in intercept_unary_unary
    return continuation(client_call_details, request)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_interceptor.py", line 217, in continuation
    credentials=new_credentials)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 536, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
```
	details = ""
	debug_error_string = "{"created":"@1584969280.312128450","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1099,"grpc_message":"","grpc_status":2}"
>
../../utils/Makefile:27: recipe for target 'run' failed
make: *** [run] Error 1

**Comment by jnfoster** [comment]
This is the repository for tracking technical issues in the P4 tutorial source code, not questions about specific programs.

I suspect you'll get a faster response if you ask your question on the [p4-dev](http://lists.p4.org/mailman/listinfo/p4-dev_lists.p4.org) list or the [P4 Slack](https://p4-lang.slack.com/join/shared_invite/enQtODA0NzY4Mjc5MTExLTRlMWVmN2I5ZTY4MTAzMDI3MGQ1OTZjM2ZmM2Q1MWE2YzZjYTQ2ZWMyMGUyYjQ2ZmIxMjFjZDE4ZThiN2ZkZWI).
