### ISSUE TITLE
Read multicast group entries

### ISSUE THREAD

**Issue by j91157j91157** [p4lang/tutorials#379]
Dear P4-Community, 
I am implementing the function of ReadMulticastGroupEntries

In the "switch.py" file in the "p4runtime_lib" folder, the code is as follows:
```python
def ReadMulticastGroupEntries(self, group_id=None, dry_run=False):
    request = p4runtime_pb2.ReadRequest()
    request.device_id = self.device_id
    entity = request.entities.add()
    mc_group_entry = entity.packet_replication_engine_entry.multicast_group_entry
    if group_id is not None:
        mc_group_entry.multicast_group_id = group_id
    else:
        mc_group_entry.multicast_group_id = 0
    if dry_run:
        print "P4Runtime Read:", request
    else:
        for response in self.client_stub.Read(request):
            yield response
```
___
Use P4 Runtime to call this function in python environment:
```python
def readGroupRules(p4info_helper, sw):
    print '\n----- Reading groups rules for %s -----' % sw.name
    for response in sw.ReadMulticastGroupEntries():
        for entity in response.entities:
            entry = entity.packet_replication_engine_entry.multicast_group_entry

            group_id = entry.multicast_group_id
            print "Group ID: ", group_id
            for p in entry.replicas:
                print "egress port & instance: ", p.egress_port,
                print '%d' % p.instance,
            print
```
___
Unfortunately, an error occurred...

It seems that the reason is that the response of multicast group entries cannot be read.
```python-traceback
Traceback (most recent call last):
  File "mycontroller.py", line 695, in <module>
    main(args.p4info, args.bmv2_json)
  File "mycontroller.py", line 665, in main
    readGroupRules(p4info_helper, p4switch)
  File "mycontroller.py", line 383, in readGroupRules
    for response in sw.ReadMulticastGroupEntries():
  File "/home/rb4/tutorials/exercises/basic/P4-isis/../../../utils/p4runtime_lib/switch.py", line 237, in ReadMulticastGroupEntries
    for response in self.client_stub.Read(request):
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 413, in next
    return self._next()
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 689, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "Reading from PRE is not supported yet"
	debug_error_string = "{"created":"@1599156351.038124396","description":"Error received from peer ipv4:127.0.0.1:50051","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Reading from PRE is not supported yet","grpc_status":12}"

```
___
When I turn on the "dry_run" parameter in the "ReadMulticastGroupEntries" function, displays as follows:
```p4
P4Runtime Read: entities {
  packet_replication_engine_entry {
    multicast_group_entry {
    }
  }
}
```
It is certain that "ReadRequest" is correct, but what puzzles me is that I don't know where the problem is.

for whether P4Runtime does not currently support this function?

**Comment by antoninbas** [comment]
You are getting this error message: `"Reading from PRE is not supported yet"`. Since this has been supported for a while now, I assume you are using a tutorials VM and that the software that's included is just too old and does not include support for this. @jafingerhut maintains scripts that you can use to install the latest versions of all the p4lang software on a fresh VM: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

**Comment by j91157j91157** [comment]
@antoninbas  Thank you very much!

Follow your suggestions to upgrade all software to the latest version, it's work!!
```
----- Reading groups rules for p4switch -----
Group ID:  2
egress port & instance:  0 1

Group ID:  1
egress port & instance:  0 1
egress port & instance:  1 1
```
