### ISSUE TITLE
Building mininet topology. Traceback (most recent call last):   File "/home/snsrl3/Documents/tutorials-master/exercises/basic_tunnel/../../utils/run_exercise.py", line 387, in <module>     exercise.run_exercise()   File "/home/snsrl3/Documents/tutorials-master/exercises/basic_tunnel/../../utils/run_exercise.py", line 195, in run_exercise     self.create_network()   File "/home/snsrl3/Documents/tutorials-master/exercises/basic_tunnel/../../utils/run_exercise.py", line 256, in create_network     self.net = Mininet(topo = self.topo,   File "/usr/local/lib/python3.10/dist-packages/mininet/net.py", line 178, in __init__     self.build()

### ISSUE THREAD

**Issue by LavanyaMalakalapalli** [p4lang/tutorials#530]

**Comment by jafingerhut** [comment]
How did you install the open source P4 development tools on your system?

What command did you run that gave these errors?
